/**
 * GitHub Preset Emojis
 */
export const PRESET_EMOJIS = [
    { emoji: '😊', name: 'smile' },
    { emoji: '😄', name: 'grin' },
    { emoji: '😆', name: 'laughing' },
    { emoji: '😅', name: 'sweat_smile' },
    { emoji: '🤣', name: 'rofl' },
    { emoji: '😂', name: 'joy' },
    { emoji: '🙂', name: 'slightly_smiling_face' },
    { emoji: '🙃', name: 'upside_down_face' },
    { emoji: '🫠', name: 'melting_face' },
    { emoji: '😉', name: 'wink' },
    { emoji: '😌', name: 'relieved' },
    { emoji: '😍', name: 'heart_eyes' },
    { emoji: '🥰', name: 'smiling_face_with_hearts' },
    { emoji: '😘', name: 'kissing_heart' },
    { emoji: '😗', name: 'kissing' },
    { emoji: '😙', name: 'kissing_smiling_eyes' },
    { emoji: '😚', name: 'kissing_closed_eyes' },
    { emoji: '😋', name: 'yum' },
    { emoji: '😛', name: 'stuck_out_tongue' },
    { emoji: '😝', name: 'stuck_out_tongue_closed_eyes' },
    { emoji: '😜', name: 'stuck_out_tongue_winking_eye' },
    { emoji: '🤪', name: 'zany_face' },
    { emoji: '🤨', name: 'raised_eyebrow' },
    { emoji: '🧐', name: 'monocle_face' },
    { emoji: '🤓', name: 'nerd_face' },
    { emoji: '😎', name: 'sunglasses' },
    { emoji: '🥳', name: 'partying_face' },
    { emoji: '😏', name: 'smirk' },
    { emoji: '😒', name: 'unamused' },
    { emoji: '😞', name: 'disappointed' },
    { emoji: '😔', name: 'pensive' },
    { emoji: '😟', name: 'worried' },
    { emoji: '😕', name: 'confused' },
    { emoji: '🙁', name: 'slightly_frowning_face' },
    { emoji: '☹️', name: 'frowning_face' },
    { emoji: '😣', name: 'persevere' },
    { emoji: '😖', name: 'confounded' },
    { emoji: '😫', name: 'tired_face' },
    { emoji: '😩', name: 'weary' },
    { emoji: '🥺', name: 'pleading_face' },
    { emoji: '😢', name: 'cry' },
    { emoji: '😭', name: 'sob' },
    { emoji: '😤', name: 'triumph' },
    { emoji: '😠', name: 'angry' },
    { emoji: '😡', name: 'rage' },
    { emoji: '🤬', name: 'face_with_symbols_on_mouth' },
    { emoji: '🤯', name: 'exploding_head' },
    { emoji: '😳', name: 'flushed' },
    { emoji: '🥵', name: 'hot_face' },
    { emoji: '🥶', name: 'cold_face' },
    { emoji: '😱', name: 'scream' },
    { emoji: '😨', name: 'fearful' },
    { emoji: '😰', name: 'cold_sweat' },
    { emoji: '😥', name: 'disappointed_relieved' },
    { emoji: '😓', name: 'sweat' },
    { emoji: '🤗', name: 'hugs' },
    { emoji: '🤔', name: 'thinking' },
    { emoji: '🤭', name: 'hand_over_mouth' },
    { emoji: '🤫', name: 'shushing_face' },
    { emoji: '🤥', name: 'lying_face' },
    { emoji: '😶', name: 'no_mouth' },
    { emoji: '😐', name: 'neutral_face' },
    { emoji: '😑', name: 'expressionless' },
    { emoji: '😬', name: 'grimacing' },
    { emoji: '🙄', name: 'rolling_eyes' },
    { emoji: '😯', name: 'hushed' },
    { emoji: '😦', name: 'frowning' },
    { emoji: '😧', name: 'anguished' },
    { emoji: '😮', name: 'open_mouth' },
    { emoji: '😲', name: 'astonished' },
    { emoji: '🥱', name: 'yawning_face' },
    { emoji: '😴', name: 'sleeping' },
    { emoji: '🤤', name: 'drooling_face' },
    { emoji: '😪', name: 'sleepy' },
    { emoji: '😵', name: 'dizzy_face' },
    { emoji: '🤐', name: 'zipper_mouth_face' },
    { emoji: '🥴', name: 'woozy_face' },
    { emoji: '🤢', name: 'nauseated_face' },
    { emoji: '🤮', name: 'vomiting_face' },
    { emoji: ' sneezeing_face', name: 'sneezing_face' },
    { emoji: '😷', name: 'mask' },
    { emoji: '🤒', name: 'face_with_thermometer' },
    { emoji: '🤕', name: 'face_with_head_bandage' },
    { emoji: '🏝️', name: 'vacation' },
    { emoji: '🏠', name: 'home' },
    { emoji: '💻', name: 'laptop' },
    { emoji: '☕', name: 'coffee' },
    { emoji: '🎮', name: 'gaming' },
    { emoji: '📚', name: 'books' },
    { emoji: '🎵', name: 'music' },
];

/**
 * Common Status Presets
 */
export const PRESET_STATUSES = [
    { emoji: '🏝️', text: 'On vacation', label: '🏝️ On vacation' },
    { emoji: '🤒', text: 'Out sick', label: '🤒 Out sick' },
    { emoji: '🏠', text: 'Working from home', label: '🏠 Working from home' },
    { emoji: '💻', text: 'Focusing', label: '💻 Focusing' },
];

/**
 * Expiration Options for Status
 */
export const EXPIRATION_OPTIONS = [
    { value: 'never', label: 'Never' },
    { value: '30min', label: 'In 30 minutes' },
    { value: '1hour', label: 'In 1 hour' },
    { value: '4hours', label: 'In 4 hours' },
    { value: 'today', label: 'After today' },
    { value: 'week', label: 'After this week' },
    { value: 'month', label: 'After a month' },
];
