"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _home_sidebar from './home-sidebar.bones.json'
import _home_feed from './home-feed.bones.json'
import _copilot from './copilot.bones.json'
import _global_repo_list from './global-repo-list.bones.json'
import _repo_list from './repo-list.bones.json'

registerBones({
  "home-sidebar": _home_sidebar,
  "home-feed": _home_feed,
  "copilot": _copilot,
  "global-repo-list": _global_repo_list,
  "repo-list": _repo_list,
})
